SET SERVEROUTPUT ON;

-- 1
DECLARE 
    E_ID NUMBER:= 101; -- INPUT EMPLOYEE_ID HERE
    E_FNAME EMPLOYEES.FIRST_NAME%TYPE;
    E_LNAME EMPLOYEES.LAST_NAME%TYPE;
    E_SAL EMPLOYEES.SALARY%TYPE;
    D_ID DEPARTMENTS.DEPARTMENT_ID%TYPE;
    D_NAME DEPARTMENTS.DEPARTMENT_NAME%TYPE;
BEGIN
    SELECT E.FIRST_NAME, E.LAST_NAME, E.SALARY, D.DEPARTMENT_ID, D.DEPARTMENT_NAME
    INTO E_FNAME, E_LNAME, E_SAL, D_ID, D_NAME
    FROM EMPLOYEES E 
    JOIN DEPARTMENTS D 
        ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    WHERE E.EMPLOYEE_ID = E_ID;
    
    DBMS_OUTPUT.PUT_LINE('ID: ' || E_ID);
    DBMS_OUTPUT.PUT_LINE('NAME: ' || E_FNAME || ' ' || E_LNAME);
    DBMS_OUTPUT.PUT_LINE('SALARY: ' || E_SAL);
    DBMS_OUTPUT.PUT_LINE('DEPARTMENT ID: ' || D_ID);
    DBMS_OUTPUT.PUT_LINE('DEPARTMENT: ' || D_NAME);
END;
/

-- 2
